# Generated by Django 4.1.6 on 2023-02-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_link",
            field=models.CharField(
                default="https://via.placeholder.com/300", max_length=255
            ),
        ),
    ]
